import type { CollectionConfig } from 'payload'

export const DiagnosticSubmissions: CollectionConfig = {
  slug: 'diagnostic-submissions',
  admin: {
    useAsTitle: 'email',
    defaultColumns: ['email', 'companyName', 'reportStatus', 'createdAt'],
    description: 'Submissions from the diagnostics form. Reports are generated by AI on demand.',
  },
  // No creation from admin — submissions come from the public form
  access: {
    create: () => false,
  },
  fields: [
    {
      name: 'email',
      type: 'email',
      required: true,
    },
    {
      name: 'firstName',
      type: 'text',
    },
    {
      name: 'companyName',
      type: 'text',
    },
    {
      name: 'annualRevenue',
      type: 'select',
      label: 'Annual revenue range',
      options: [
        { label: 'Under $1M', value: 'under-1m' },
        { label: '$1M – $2M', value: '1m-2m' },
        { label: '$2M – $4M', value: '2m-4m' },
        { label: 'Over $4M', value: 'over-4m' },
      ],
    },
    {
      name: 'responses',
      type: 'json',
      label: 'Form responses',
      admin: { description: 'Raw answers from the multi-step diagnostic form.' },
    },
    {
      name: 'reportStatus',
      type: 'select',
      defaultValue: 'pending',
      options: [
        { label: 'Pending', value: 'pending' },
        { label: 'Generating', value: 'generating' },
        { label: 'Ready', value: 'ready' },
        { label: 'Failed', value: 'failed' },
      ],
    },
    {
      name: 'reportFile',
      type: 'upload',
      relationTo: 'media',
      label: 'Generated PDF report',
      admin: { condition: (data) => data?.reportStatus === 'ready' },
    },
    {
      name: 'aiPromptSnapshot',
      type: 'textarea',
      label: 'AI prompt used',
      admin: {
        description: 'Stored for debugging and reproducibility.',
        readOnly: true,
      },
    },
    {
      name: 'createdAt',
      type: 'date',
      admin: { position: 'sidebar', readOnly: true },
    },
  ],
}
